APT::FTPArchive::Release::Origin "Himosoft";
APT::FTPArchive::Release::Label "Himosoft Mirror";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64 all";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Himosoft server packages";
